### ISSUE TITLE
[$2.500] Bounty: Assign Custom Variables from Generic Http Module GET

### ISSUE THREAD

**Issue by abebeos** [bitfocus/companion-module-generic-http#27]
(subjects issue #24. Text here is updated during ongoing work.)

## Requirements

* Uses the existent variable system
* GET requests should be able to set the variable
* Solution should be backwards-compatible (not breaking any stuff)
* Add the functionality to the `generic-http` UI, see [comment](https://github.com/bitfocus/companion-module-generic-http/issues/24#issuecomment-1027288038)

## Tasks
- [x] Basic Work-In
- [x] order Streamdeck
- [x] Setup General Dev-System
- [x] Setup Specific Dev-System (2 modules, one sets the var, one consumes it)
- [x] Determine solution path
  - [x] Determine alternate solution paths, if necessary (e.g. special use-cases)
- [x] (currently active) implement
  - [x] test with emulator
  - [x] test with real hardware
- [x] publish PR https://github.com/bitfocus/companion-module-generic-http/pull/28
  - [x] update dropdowns with `NO VARIABLE` selections
  - [x] update with generic JSONPath query 
- [x] decide where to move data-extraction actions
  - [x] Implement, publish PR https://github.com/bitfocus/companion-module-bitfocus-companion/pull/50
- [x] verify based on core-team/customer feedback
- [x] refine
- [ ] finalize (target date: 15th Feb. 2022, possibly few days more for merge)

## Solution Path

My RA so far (= non-code work result) leads to this:

### http module
* provided within https://github.com/bitfocus/companion-module-generic-http/pull/28
  * extend the usual `http GET` action with a custom-variable drop-down field
  * if blank, backward-compatible, nothing changes
  * if a variable is selected:
    * assign the whole json result to the selected var

Then:

### internal module

fulfilled within: https://github.com/bitfocus/companion-module-bitfocus-companion/pull/50

JSONPath query should possibly happen at this location (core code): https://github.com/bitfocus/companion-module-bitfocus-companion/blob/fcaedc0b857b3d42377b7dfb60ca1126522b1628/index.js#L786

* provide actions which extract values from a json result (stored in a custom var)
  * This could(!) be implemented initially in a manual way (one action per variable), later in a more automated/simplified way (e.g. multiple variable assignments with one action, e.g. by providing a list of fields and a variable prefix). 
* users can provide own actions whenever necessary (e.g. special JSON data), making the solution very modular and extensible

This solution path should provide high flexibility (including prototyping etc.) whilst providing full backwards-compatibility and good maintainability, as there is not much new core code.

## Follow-up Tasks

* Simplified Help-System
* Simplified Test-System
* Refactoring or core modules
* Architectural Design re Variable/Data-Handling
* Align Visual Design to more complex Programming Needs
* Documentation

-----

@JeffreyDavidsz , @Julusian , @estilles, @haakonnessjoen 

## $2.500 bounty

There is a bounty on this issue #24, see

(https://app.bountysource.com/issues/105114232-add-the-ability-ability-to-set-custom-variable-values-with-an-http-request).

I started work on this a week ago and planned to deliver until 15th Feb. My current (unpublished) result is similar to this within #25 (by @mertmit, another bounty-worker,  independent of me).

See above for my work-progress

## Core Team Matter

During my in-parallel implementation-work and further requirements-analysis, I get more and more the feeling that providing this new generic functionality to the `generic http module` is something that the core-developers should do, simply because it can be implemented in different ways (and places), which would affect the overall usability of the companion product.

**Please verify if any of the core-developers would like to do the work and claim the bounty.** 

Though I've invested already many time (mostly Companion work-in) and a bit money, too (should receive my Streamdeck today), I would back-off from the bounty and leave it to a core-team-member.

If no team-member wants to claim the bounty, I would continue my work.

**Comment by JeffreyDavidsz** [comment]
We need to discuss this internally on how to proceed. Main goal would still be to support as many devices as possible. Implementing this would encourage users to use this module instead of creating a new one. 
Regarding to the Bounty I know the person who posted it, so I'm sure we can work it out to split it according to work. Further on I see @Julusian has self assigned, so there will be a good solution for this.

**Comment by JeffreyDavidsz** [comment]
Note for myself (Ember+ is a bit the same)

**Comment by abebeos** [comment]
@JeffreyDavidsz , @Julusian , I had a good momentum and used it to update https://github.com/bitfocus/companion-module-generic-http/pull/28, which should( now be already a decent draft solution. I'll most possibly update it once more to add standard  `JSONpath` data extraction, to make it usable for a broader audience.

Integrating/completing this is nearly impossible for me without additional effort from the core-team, so I'm anyways fine with splitting the bounty. **In the end, core-team decides, because the usual rule is "no merge, no bounty".**

One tiny problem: I could not find an elegant way to have a "None" selection in the variables drop-downs. What I have now is not usable for production (would prefer a clearly visible `<No Variable Selected>` or similar top-most). Possibly you can comment at the PR.

(As a sidenote: I like the project much, as I miss hardware-design, it's nice to see something actually happening when coding. The enhancement/extension of the core-code, developer and end-user usability looks quite a challenge.)

**Comment by abebeos** [comment]
I believe that #28 is now close to an optimal solution, using a standard-based JSONpath query. This allows simple paths like"$.name" (or even just "name", as it seems) or more complex ones.

Guess the action would become a `custom_variable_from_json_path` or `custom_variable_from_json_result` within the internal module.

Momentum is gone, will await now your feedback.

**Comment by JeffreyDavidsz** [comment]
@abebeos some modules are created for a bounty most are made in free time. Regarding to bitfocus-companion; there is a rewrite going on for that by the core team. No bounties for that, in the past we did some if there was an issue we could not solve. If you would like to help growing Companion and make the product better, please let us know, of course contribution on modules is already very helpful.
I'll close this issue and see if I can merge your pull-request. If all ok and with no further comment I'll give Austin a go for the bounty

**Comment by abebeos** [comment]
> If all ok and with no further comment I'll give Austin a go for the bounty

@JeffreyDavidsz , the bounty claim on bountysource needs to be accepted by @amcchord, otherwise the payout will take 2 weeks.

**Comment by JeffreyDavidsz** [comment]
@abebeos thanks for your work, I've had no time to test but the code looks good. I'll let Austin know

**Comment by abebeos** [comment]
Ok, thank you. I'm still active on the project for the next days, so if anything comes up, just let me know (though I believe @Julusian has anyway full control of the few new lines of code)

**Comment by abebeos** [comment]
@JeffreyDavidsz , received, thanks a lot!

**Comment by abebeos** [comment]
@JeffreyDavidsz , @haakonnessjoen (not sure who to ping, and if pings work within closed issues)

> If you would like to help growing Companion and make the product better

I noticed that rewrites are ongoing since 2 years. I believe that the 2.* line can be modernized without the need to change the overall design fully, thus the original design can more or less 'survive', allowing all developers which worked on the code to contribute witout then need to understand new designs/code. (executing smaller steps within a timeframe of 3 months).

See here for a suggestion:

https://github.com/abebeos/companion/issues/1

**Comment by JeffreyDavidsz** [comment]
@abebeos it would be good to discuss this further on slack. Are you on slack? You can find the link in the software.

**Comment by abebeos** [comment]
I do not use chat-systems professionally (prefere docs, issues, email), but joined the Bitfocus AS Slack to make it easier for you.

**Comment by Julusian** [comment]
> I noticed that rewrites are ongoing since 2 years.

Kind of, but we decided to do it post 2.2. And then we started fresh with it the other week. The other work was abandoned prototyping, so not entirely relevant

**Comment by abebeos** [comment]
"abandoned prototyping" is a "rewrite attempt", thus relevant.

I believe that my statement "rewrites are ongoing since 2 years" is valid.

**Comment by abebeos** [comment]
@willosof?

**Comment by Jibun-no-Kage** [comment]
Is there an example of how this can be leveraged or used?  I have an application that I can query its REST API for state of a given feature being enabled or disabled, and I would like Companion to set a custom variable to that value, which then in turn I could use said value to set button text, background color, etc. via feedback.

**Comment by JeffreyDavidsz** [comment]
When it is posible to use variables in a text box just copy paste the variable you want to use where you want to use it
